WebFinal/Areas/Admin/Controllers/AccountAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFinal.Models;

namespace WebFinal.Areas.Admin.Controllers
{
    public class AccountAdminController : Controller
    {
        // GET: Admin/AccountAdmin
        EcommerceEntities _dbContext = new EcommerceEntities();
        [HttpGet]
        // GET: Admin
        public ActionResult Login()
        {

            return View();
        }

      //  [HttpPost]
        // Post: Admin
        //public ActionResult Login(tb_Admin admin)
        //{
        //    tb_Admin ad = _dbContext.tb_Admin.Where(x => x.userName == admin.userName && x.password == admin.password).SingleOrDefault();
        //    if (ad != null)
        //    {
        //        Session["idAdmin"] = ad.idAdmin.ToString();
        //        return RedirectToAction("ViewCategory", "View", new { area = "Admin" });
        //    }
        //    else
        //    {
        //        ViewBag.error = "Sai mật khẩu hoặc tài khoản";
        //    }
        //    return View();
        
    }
}

WebFinal/Areas/Admin/Views/AccountAdmin/Login.cshtml
@model WebFinal.Models.tb_Admin
@{
    ViewBag.Title = "Login";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAccount.cshtml";
}

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
            @using (Html.BeginForm("Login", "AccountAdmin", FormMethod.Post))
            {
                <form class="login100-form validate-form">


                    <h3 class="login100-form-title p-b-33">
                        Đăng Nhập
                    </h3>

                    <div class="wrap-input100 validate-input" data-validate="Không để trống tài khoản">

                        @Html.TextBoxFor(x => x.userName, new { @class = "form-control input100", @placeholder = "Tài Khoản" })
                        @Html.ValidationMessageFor(x => x.userName)

                    </div>

                    <div class="wrap-input100 rs1 validate-input" data-validate="Yêu cầu nhập mật khẩu">

                        @Html.PasswordFor(x => x.password, new { @class = "form-control input100", @placeholder = "Mật Khẩu" })
                        @Html.ValidationMessageFor(x => x.password)

                    </div>
                    <div class="container-login100-form-btn m-t-20">
                        <p style="color:red">@ViewBag.error</p>

                    </div>
                    <div class="container-login100-form-btn m-t-20">
                        <input class="login100-form-btn" type="submit" value="Đăng Nhập" />
                    </div>

                    <div class="text-center p-t-45 p-b-4">
                        <span class="txt1">
                            Quên
                        </span>

                        <a href="#" class="txt2 hov1">
                            Mật khẩu?
                        </a>
                    </div>

                    <div class="text-center">
                        <span class="txt1">
                            Đăng ký?
                        </span>

                        @*  @Html.ActionLink("Đăng Ký", "Register", "User")*@
                    </div>


                </form>
            }

        </div>
    </div>
</div>